# Funding options for SaferTrade
# Uncomment and configure the platforms you use

# github: hallosoares
# patreon: safertrade
# open_collective: safertrade
# ko_fi: safertrade
# custom: ['https://safertrade.io/donate']
