# Issue and PR labels for SaferTrade
# Apply using: https://github.com/marketplace/actions/github-labeler

- name: bug
  color: d73a4a
  description: Something is not working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: good-first-issue
  color: 7057ff
  description: Good for newcomers

- name: help-wanted
  color: 008672
  description: Extra attention is needed

- name: security
  color: d93f0b
  description: Security related issues

- name: engine
  color: fbca04
  description: Related to detection engines

- name: api
  color: 1d76db
  description: Related to API endpoints

- name: performance
  color: 5319e7
  description: Performance improvements

- name: stale
  color: ffffff
  description: No recent activity

- name: duplicate
  color: cfd3d7
  description: This issue or PR already exists

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: question
  color: d876e3
  description: Further information is requested
